language: dart

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.pub-cache

dart:
  - dev

dart_task:
  - dartanalyzer: --fatal-warnings --lints .
  - dartfmt
  - test

# Run tests on lowest supported SDK version.
matrix:
  include:
  - dart: 2.12.0
    dart_task: test
