name: path_to_regexp
version: 0.4.0
description: Converts a path such as '/user/:id' into a regular expression.
homepage: https://github.com/leonsenft/path_to_regexp

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  # For `package:pedantic/analysis_options.yaml`.
  pedantic: 1.11.0
  test: ^1.16.5
